#DATABASE
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

  #JPA
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    properties:
      hibernate:
        dialect: