#DATABASE
spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver 

#JPA
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true       
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect