#DATABASE
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  #JPA
  jpa:
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL_AUTO}
    show-sql: ${DB_SHOW_SQL}
    dialect: ${DB_DIALECT}